---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: frontier-latest
  namespace: frontier-analytics
spec:
  interval: 3m0s
  ref:
    branch: main
  url: https://github.com/ATLAS-Analytics/Frontier-deployment

