apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontier-analytics-deployment
  namespace: frontier-analytics
  labels:
    app: frontier-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontier-analytics
  template:
    metadata:
      labels:
        app: frontier-analytics
    spec:
      containers:
        - name: web-server
          image:  docker.io/atlasanalyticsservice/frontier:70cd302ccbaeb696c3b1feaac2a8dc7d0f3c6b98
          command:
            - "sleep"
            # - "python3"
          args:
            - "3600"
            # - "/home/frntmon/FrontierAnalyticsApp.py"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "16Gi"
            limits:
              memory: "16Gi"
          env:
            - name: PYTHONUNBUFFERED
              value: "0"
            - name: FrontierAnalyticsApp_SETTINGS
              value: "/home/frntmon/settings.cfg"
            - name: CELERY_URL
              value: "redis://redis-master.frontier-analytics.svc.cluster.local:6379"
          volumeMounts:
            - name: config-volume
              mountPath: "/home/frntmon/"
            - name: analytics-config-volume
              mountPath: "/Analytics/FrontierData/Config"
            - name: data-volume
              mountPath: "/home/frntmon/ParquetDirectory"
            - name: coolr-volume
              mountPath: "/home/frntmon/Files"

        - name: celery-server
          image:  docker.io/atlasanalyticsservice/frontier_analytics:7295647eb37dbc8e196a8d18da2b181013a77285
          imagePullPolicy: Always
          resources:
            requests:
              memory: "16Gi"
            limits:
              memory: "16Gi"
          env:
            - name: PYTHONUNBUFFERED
              value: "0"
            - name: CONFIG_FILE
              value: "/home/frntmon/celery-queue/configs/configuration.txt"
            - name: CELERY_URL
              value: "redis://redis-master.frontier-analytics.svc.cluster.local:6379"
          volumeMounts:
            - name: analytics-config-volume
              mountPath: "/home/frntmon/celery-queue/configs"
            - name: coolr-volume
              mountPath: "/home/frntmon/Files"
            - name: data-volume
              mountPath: "/home/frntmon/ParquetDirectory"
      volumes:
        - name: config-volume
          configMap:
            name: flask-config
        - name: analytics-config-volume
          secret:
            secretName: analytics-config
            items:
              - key: config
                path: configuration.txt
        - name: coolr-volume
          emptyDir: {}
        - name: data-volume
      nodeSelector:
        nologs: "false"
