name: Update Frontier Analytics Image Reference
on:
  repository_dispatch:
    types: gitops-frontier-analytics-trigger
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v4.1.6
      - name: Update Version In Checked-Out Code
        if: ${{ github.event.client_payload.sha }}
        run: |
          sed -i "s@\(docker.io/atlasanalyticsservice/frontier_analytics:\).*@ docker.io/atlasanalyticsservice/frontier_analytics:${{ github.event.client_payload.sha }}@" ${GITHUB_WORKSPACE}/deploy/prod/deployment.yaml
      - name: Commit The New Image Reference
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        if: ${{ github.event.client_payload.sha }}
        with:
          commit_message: Deploy new image ${{ github.event.client_payload.sha }}
          branch: main
          commit_options: "--no-verify --signoff"
          repository: .
          commit_user_name: Frontier GitOps Bot
          commit_user_email: ilijav@gmail.com
          commit_author: Frontier GitOps Bot <ilijav@gmail.com>
